#!/usr/bin/env python3
"""Generate styles/ios10-layout.css from styles/sidecrab.css.

WHY THIS EXISTS. Measured on an iPad 4 / iOS 10.3.3 with widget/compat-test.html:
Safari 10 answers `no` to EVERY media query in the stylesheet that carries a
`max-aspect-ratio` term — including the two that are plainly true on a 1024x768
screen. `(max-width: 1800px)` and `(max-width: 1200px)` are the only two of the
eight that match. So the four <=3:2 layout blocks never apply, and the panel is
left in the (max-width: 1200px) state, which hides the Limits zone outright:

    @media (max-width: 1200px) { .zone-limits { display: none; } }

Upstream restates `display: flex` for exactly that collision in the NEAR-SQUARE
block (sidecrab.css:3423) — but that block is gated on the aspect ratio the
browser will not evaluate, so the restatement never runs.

WHAT THIS DOES. Copies those four blocks verbatim, dropping only the
`(max-aspect-ratio: ...)` term from each prelude, and wraps each one in
`@supports not (gap: 1px)` so nothing reaches a browser that could have
evaluated the original. Comments are kept: they are upstream's reasoning about
measured pixel budgets, and a generated file nobody can review is worse than no
generated file.

WHAT IS GIVEN UP, and it is a real trade. Without the ratio term the condition
is width/height minimums alone, so a LEGACY browser on a wide-but-tall-enough
window gets a layout meant for a near-square slot. The @supports gate keeps it
away from every browser with flexbox gap (Safari 14.1+, and Chromium 130 on the
Xeneon Edge — which at 2560x720 clears both minimums and would otherwise be
re-laid-out into the near-square design, i.e. this gate is load-bearing, not
tidiness). The residual is a pre-14.1 Safari on a wide window. No such device is
in play here, and the alternative — approximating a ratio test with paired
width/height ranges — trades a small known error for a large unreadable one.

RUN IT AFTER EVERY UPSTREAM MERGE:

    python3 widget/tools/gen-ios10-layout.py

and commit the result. If sidecrab.css moves those blocks, the regenerated file
follows; if it stops having them, this exits non-zero rather than emitting a
file that silently no longer matches anything.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "..", "styles", "sidecrab.css")
OUT = os.path.join(HERE, "..", "styles", "ios10-layout.css")

src = open(BASE, encoding="utf-8").read()
lines = src.split("\n")

HEADER = """/* GENERATED by widget/tools/gen-ios10-layout.py — DO NOT EDIT BY HAND.
   Regenerate after every `git merge upstream/main`; see that script for why.

   Safari 10 evaluates no media query carrying `max-aspect-ratio`, so the four
   <=3:2 layout blocks in sidecrab.css never apply on an iPad 4 and the panel is
   stranded in the (max-width: 1200px) state — which hides the Limits zone. Each
   block below is that block verbatim, with only the ratio term removed from its
   prelude, gated so it cannot reach a browser that would have matched properly.

   Source blocks: sidecrab.css lines %s. */

"""


def find_blocks():
    """Every top-level @media whose prelude mentions max-aspect-ratio."""
    out = []
    for i, line in enumerate(lines):
        if not line.startswith("@media") or "max-aspect-ratio" not in line:
            continue
        depth, body = 0, []
        for j in range(i, len(lines)):
            body.append(lines[j])
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0 and j > i:
                break
        out.append((i + 1, body))
    return out


def strip_ratio(prelude):
    """`@media (max-aspect-ratio: 3/2) and (min-height: 421px) {` ->
       `@media (min-height: 421px) {`   — and the lone-term case to `all`."""
    p = re.sub(r"\(\s*max-aspect-ratio\s*:[^)]*\)\s*and\s*", "", prelude)
    p = re.sub(r"\s*and\s*\(\s*max-aspect-ratio\s*:[^)]*\)", "", p)
    if re.match(r"^@media\s*\{", p.strip()):
        p = "@media all {"
    return p


blocks = find_blocks()
if not blocks:
    sys.exit("gen-ios10-layout: no max-aspect-ratio media blocks in sidecrab.css — "
             "upstream changed shape; this script needs rereading, not rerunning.")

chunks = []
for start, body in blocks:
    prelude = strip_ratio(body[0])
    inner = body[1:-1]
    chunks.append(
        "/* ---- sidecrab.css:%d ----\n   was: %s */\n@supports not (gap: 1px) {\n%s\n%s\n}\n}\n"
        % (start, body[0].strip(), prelude, "\n".join(inner))
    )

CORRECTIONS = """

/* =====================================================================
   Hand-maintained: gap fallbacks these layouts invalidate
   =====================================================================

   NOT generated — regenerating the file above must not drop this.

   ios10-compat.css replaces every `gap` with a margin, and the axis it picks is
   the container's flex-direction AT THE AUTHORED SLOT. Two of the blocks above
   flip a direction, which silently turns the right margin into the wrong one:

     NEAR-SQUARE flips .zone-identity to `flex-direction: row` (sidecrab.css:3419)
     PORTRAIT    flips .zone-limits   to `flex-direction: row` (sidecrab.css:3523)

   Both were column at the 2560x720 slot, so both carry a margin-top from the
   compat layer that has to become a margin-left here. The auto margins are
   re-cleared for the same reason they were asserted there: on a row they anchor
   nothing and would push their sibling to the far edge. */

@supports not (gap: 1px) {
	@media (min-height: 421px) and (min-width: 641px) {
		.zone-identity > * + * { margin-top: 0; margin-left: calc(var(--layout-unit) * 2.2); }
	}
	@media (min-height: 421px) and (max-width: 640px) {
		.zone-limits > * + * { margin-top: 0; margin-left: var(--space-gap); }
		.zone-limits > .today,
		.zone-limits > .sensors.shown { margin-top: 0; }
	}
}
"""

ref = ", ".join(str(s) for s, _ in blocks)
open(OUT, "w", encoding="utf-8").write(HEADER % ref + "\n".join(chunks) + CORRECTIONS)
print("gen-ios10-layout: %d blocks -> %s" % (len(blocks), os.path.normpath(OUT)))
