#!/usr/bin/env python3
"""Generate styles/ios10-layout.css from styles/sidecrab.css.

WHY THIS EXISTS. Measured on an iPad 4 / iOS 10.3.3 with widget/compat-test.html:
Safari 10 answers `no` to EVERY media query in the stylesheet that carries a
`max-aspect-ratio` term — including the two that are plainly true on a 1024x768
screen. `(max-width: 1800px)` and `(max-width: 1200px)` are the only two of the
eight that match. So the four <=3:2 layout blocks never apply, and the panel is
left in the (max-width: 1200px) state, which hides the Limits zone outright:

    @media (max-width: 1200px) { .zone-limits { display: none; } }

Upstream restates `display: flex` for exactly that collision in the NEAR-SQUARE
block (sidecrab.css:3423) — but that block is gated on the aspect ratio the
browser will not evaluate, so the restatement never runs.

WHAT THIS DOES. Copies those four blocks verbatim, dropping only the
`(max-aspect-ratio: ...)` term from each prelude, and wraps each one in
`@supports not (gap: 1px)` so nothing reaches a browser that could have
evaluated the original. Comments are kept: they are upstream's reasoning about
measured pixel budgets, and a generated file nobody can review is worse than no
generated file.

WHAT IS GIVEN UP, and it is a real trade. Without the ratio term the condition
is width/height minimums alone, so a LEGACY browser on a wide-but-tall-enough
window gets a layout meant for a near-square slot. The @supports gate keeps it
away from every browser with flexbox gap (Safari 14.1+, and Chromium 130 on the
Xeneon Edge — which at 2560x720 clears both minimums and would otherwise be
re-laid-out into the near-square design, i.e. this gate is load-bearing, not
tidiness). The residual is a pre-14.1 Safari on a wide window. No such device is
in play here, and the alternative — approximating a ratio test with paired
width/height ranges — trades a small known error for a large unreadable one.

RUN IT AFTER EVERY UPSTREAM MERGE:

    python3 widget/tools/gen-ios10-layout.py

and commit the result. If sidecrab.css moves those blocks, the regenerated file
follows; if it stops having them, this exits non-zero rather than emitting a
file that silently no longer matches anything.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "..", "styles", "sidecrab.css")
OUT = os.path.join(HERE, "..", "styles", "ios10-layout.css")

src = open(BASE, encoding="utf-8").read()
lines = src.split("\n")

HEADER = """/* GENERATED by widget/tools/gen-ios10-layout.py — DO NOT EDIT BY HAND.
   Regenerate after every `git merge upstream/main`; see that script for why.

   Safari 10 evaluates no media query carrying `max-aspect-ratio`, so the four
   <=3:2 layout blocks in sidecrab.css never apply on an iPad 4 and the panel is
   stranded in the (max-width: 1200px) state — which hides the Limits zone. Each
   block below is that block verbatim, with only the ratio term removed from its
   prelude, gated so it cannot reach a browser that would have matched properly.

   Source blocks: sidecrab.css lines %s. */

"""


def find_blocks():
    """Every top-level @media whose prelude mentions max-aspect-ratio."""
    out = []
    for i, line in enumerate(lines):
        if not line.startswith("@media") or "max-aspect-ratio" not in line:
            continue
        depth, body = 0, []
        for j in range(i, len(lines)):
            body.append(lines[j])
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0 and j > i:
                break
        out.append((i + 1, body))
    return out


def strip_ratio(prelude):
    """`@media (max-aspect-ratio: 3/2) and (min-height: 421px) {` ->
       `@media (min-height: 421px) {`   — and the lone-term case to `all`."""
    p = re.sub(r"\(\s*max-aspect-ratio\s*:[^)]*\)\s*and\s*", "", prelude)
    p = re.sub(r"\s*and\s*\(\s*max-aspect-ratio\s*:[^)]*\)", "", p)
    if re.match(r"^@media\s*\{", p.strip()):
        p = "@media all {"
    return p


blocks = find_blocks()
if not blocks:
    sys.exit("gen-ios10-layout: no max-aspect-ratio media blocks in sidecrab.css — "
             "upstream changed shape; this script needs rereading, not rerunning.")

chunks = []
for start, body in blocks:
    prelude = strip_ratio(body[0])
    inner = body[1:-1]
    chunks.append(
        "/* ---- sidecrab.css:%d ----\n   was: %s */\n@supports not (gap: 1px) {\n%s\n%s\n}\n}\n"
        % (start, body[0].strip(), prelude, "\n".join(inner))
    )

CORRECTIONS = """

/* =====================================================================
   Hand-maintained: gap fallbacks these layouts invalidate
   =====================================================================

   NOT generated — regenerating the file above must not drop this.

   ios10-compat.css replaces every `gap` with a margin, and the axis it picks is
   the container's flex-direction AT THE AUTHORED SLOT. Two of the blocks above
   flip a direction, which silently turns the right margin into the wrong one:

     NEAR-SQUARE flips .zone-identity to `flex-direction: row` (sidecrab.css:3419)
     PORTRAIT    flips .zone-limits   to `flex-direction: row` (sidecrab.css:3523)

   Both were column at the 2560x720 slot, so both carry a margin-top from the
   compat layer that has to become a margin-left here. The auto margins are
   re-cleared for the same reason they were asserted there: on a row they anchor
   nothing and would push their sibling to the far edge. */

@supports not (gap: 1px) {

	/* ---- THE ROOT OF EVERYTHING BELOW ----

	   .zones is `flex: 1 1 auto` with no stated height, and every height in the
	   panel is a percentage of it: the band's 29%, the two zones' 71%, .crab's
	   100%, and the `repeat(2, minmax(0, 1fr))` rows of the card grid. A flex
	   item's height is definite enough for those percentages in a modern engine
	   and NOT in this one, so all of them silently resolved to auto — which is
	   one cause with four faces: the crab inflated to its intrinsic ratio, the
	   band grew to hold it, the two zones fell off the bottom of the screen, and
	   the grid rows sized to content so two cards filled the whole zone.

	   Stating the height makes the whole chain resolvable again. flex-shrink is
	   untouched, so the banner still gets its space on the rare frame it appears. */
	.zones { height: 100%; }

	@media (min-height: 421px) and (min-width: 641px) {
		:root {
			/* TUNE THESE TWO. Everything else in this block is derived. */
			--legacy-crab-h: calc(var(--fs-clock) * 1.25);
			--legacy-band-gap: calc(var(--layout-unit) * 6);
			/* The band is the crab plus .zone's own padding, top and bottom. */
			--legacy-band-h: calc(var(--legacy-crab-h) + var(--space-pad) * 2);
		}

		/* Restated rather than inherited: this block is the one that has to hold
		   even if a later upstream edit moves the band's direction around. */
		.zone-identity {
			height: auto;
			flex-direction: row;
			align-items: center;
			justify-content: center;
		}
		/* .clock is `width: 100%` at the authored slot, where the band is a COLUMN
		   and 100% is the right answer. In a row it makes the clock as wide as the
		   whole zone, which is what put it over the crab. The shared block already
		   says `width: auto`; restated here because being wrong about this looks
		   exactly like the gap being too small, and cost a round trip to tell apart. */
		.clock { flex: 0 0 auto; width: auto; }
		.zone-identity > * + * { margin-top: 0; margin-left: var(--legacy-band-gap); }

		/* ---- the crab is sized to the clock, not to the row ----

		   .crab is `width: 100%; height: 100%` inside .crab-wrap, which is
		   `flex: 1 1 auto` with no definite height of its own. When the percentage
		   height does not resolve — which is the same missing definite-height chain
		   that stopped the sheet scrolling — an <svg> with a viewBox falls back to
		   its INTRINSIC ratio and derives its height from its width. In the
		   near-square band that width is most of 1024px, so the crab inflates to
		   several hundred px, takes the whole band with it and pushes Limits and
		   Sessions off the bottom of a screen that has body{overflow:hidden}.

		   So the band is measured off the crab rather than the other way round.
		   Height is stated in --fs-clock units to sit beside the clock by
		   construction, and the width is stated explicitly rather than left to the
		   SVG's intrinsic ratio, because relying on that ratio is what caused this.
		   52/44 is the viewBox (0 -4 52 44), so 1.182.

		   TO TUNE: change the 1.25 below and nothing else. The viewBox carries ~10
		   units of empty headroom above the shell and ~6 below the legs, so the
		   PAINTED animal is about 28 of its 44 units — the box has to run a little
		   taller than the clock for the crab to read as the same size as it. */
		   THE ORDER OF THESE TWO RULES IS A DEPENDENCY, not a preference. The shared
		   block above sets `.crab-wrap { flex: 1 1 0 }` and says why: flex-basis 0,
		   NOT auto, because `.crab { width: 100% }` inside an auto-width flex item is
		   circular — upstream measured the wrap coming out 0 px wide and the clock
		   overflowing the zone by 214 px. Going back to basis auto here is only safe
		   BECAUSE the crab below is given an explicit width in the same breath, which
		   breaks that circularity. Restore any percentage width on .crab and the wrap
		   collapses to zero and takes the clock with it. */
		.crab-wrap { flex: 0 0 auto; width: auto; }
		.crab {
			height: var(--legacy-crab-h);
			max-height: var(--legacy-crab-h);
			width: calc(var(--legacy-crab-h) * 1.182);
		}
		/* ---- the two zones take the exact remainder ----

		   Not the 71% upstream states, because the band above is now `auto` rather
		   than 29% and the two no longer add up. With .zones stated this resolves,
		   which is what finally gives .cards a definite height — and a definite
		   height is the whole reason `grid-template-rows: repeat(2, minmax(0, 1fr))`
		   can put eight cards on the glass instead of letting two fill the zone.
		   The 1px is .zone-identity's border-bottom. */
		.zone-limits,
		.zone-grid { height: calc(100% - var(--legacy-band-h) - 1px); }

		/* ---- the header stops writing over itself ----

		   The <=3:2 block gives .session-count `white-space: normal; overflow:
		   visible` so the day recap wraps instead of ellipsising — measured for an
		   840px slot, where 437px of text had 302.6px of box. A flex item that is
		   `flex: 0 1 auto; min-width: 0` and overflows VISIBLY paints outside its
		   box when the row squeezes it, and with margin-left:auto holding it right,
		   what it paints over is the "SESSIONS" label to its left.
		   This slot is 1024px, not 840, so the base one-line behaviour fits far
		   better here than it did there. Ellipsising the tail is the cost, and the
		   whole recap is one tap away: .grid-head opens today's timeline. */
		.session-count { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

		/* ---- give the density toggle back ----

		   The <=3:2 block hides it as a space trim for an 840x696 slot. Compact is
		   a THIRD grid row (12 cards, not 8) with smaller type and padding, and
		   gridCapacity() reads both axes off the computed style, so the count
		   follows the class with nothing else to change. Hiding the only control
		   that reaches it costs more than the chip's own width does here.
		   display copied from the history chip's .shown rule (sidecrab.css:1493) —
		   .head-chip states no display of its own, being a <button>. */
		.head-chip[data-density] { display: inline-flex; align-items: center; justify-content: center; }
	}
	@media (min-height: 421px) and (max-width: 640px) {
		.zone-limits > * + * { margin-top: 0; margin-left: var(--space-gap); }
		.zone-limits > .today,
		.zone-limits > .sensors.shown { margin-top: 0; }
	}
}
"""

ref = ", ".join(str(s) for s, _ in blocks)
open(OUT, "w", encoding="utf-8").write(HEADER % ref + "\n".join(chunks) + CORRECTIONS)
print("gen-ios10-layout: %d blocks -> %s" % (len(blocks), os.path.normpath(OUT)))
