#!/usr/bin/env python3
"""Generate styles/ios10-layout.css from styles/sidecrab.css.

WHY THIS EXISTS. Measured on an iPad 4 / iOS 10.3.3 with widget/compat-test.html:
Safari 10 answers `no` to EVERY media query in the stylesheet that carries a
`max-aspect-ratio` term — including the two that are plainly true on a 1024x768
screen. `(max-width: 1800px)` and `(max-width: 1200px)` are the only two of the
eight that match. So the four <=3:2 layout blocks never apply, and the panel is
left in the (max-width: 1200px) state, which hides the Limits zone outright:

    @media (max-width: 1200px) { .zone-limits { display: none; } }

Upstream restates `display: flex` for exactly that collision in the NEAR-SQUARE
block (sidecrab.css:3423) — but that block is gated on the aspect ratio the
browser will not evaluate, so the restatement never runs.

WHAT THIS DOES. Copies those four blocks verbatim, dropping only the
`(max-aspect-ratio: ...)` term from each prelude, and wraps each one in
`@supports not (gap: 1px)` so nothing reaches a browser that could have
evaluated the original. Comments are kept: they are upstream's reasoning about
measured pixel budgets, and a generated file nobody can review is worse than no
generated file.

WHAT IS GIVEN UP, and it is a real trade. Without the ratio term the condition
is width/height minimums alone, so a LEGACY browser on a wide-but-tall-enough
window gets a layout meant for a near-square slot. The @supports gate keeps it
away from every browser with flexbox gap (Safari 14.1+, and Chromium 130 on the
Xeneon Edge — which at 2560x720 clears both minimums and would otherwise be
re-laid-out into the near-square design, i.e. this gate is load-bearing, not
tidiness). The residual is a pre-14.1 Safari on a wide window. No such device is
in play here, and the alternative — approximating a ratio test with paired
width/height ranges — trades a small known error for a large unreadable one.

RUN IT AFTER EVERY UPSTREAM MERGE:

    python3 widget/tools/gen-ios10-layout.py

and commit the result. If sidecrab.css moves those blocks, the regenerated file
follows; if it stops having them, this exits non-zero rather than emitting a
file that silently no longer matches anything.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "..", "styles", "sidecrab.css")
OUT = os.path.join(HERE, "..", "styles", "ios10-layout.css")

src = open(BASE, encoding="utf-8").read()
lines = src.split("\n")

HEADER = """/* GENERATED by widget/tools/gen-ios10-layout.py — DO NOT EDIT BY HAND.
   Regenerate after every `git merge upstream/main`; see that script for why.

   Safari 10 evaluates no media query carrying `max-aspect-ratio`, so the four
   <=3:2 layout blocks in sidecrab.css never apply on an iPad 4 and the panel is
   stranded in the (max-width: 1200px) state — which hides the Limits zone. Each
   block below is that block verbatim, with only the ratio term removed from its
   prelude, gated so it cannot reach a browser that would have matched properly.

   Source blocks: sidecrab.css lines %s. */

"""


def find_blocks():
    """Every top-level @media whose prelude mentions max-aspect-ratio."""
    out = []
    for i, line in enumerate(lines):
        if not line.startswith("@media") or "max-aspect-ratio" not in line:
            continue
        depth, body = 0, []
        for j in range(i, len(lines)):
            body.append(lines[j])
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0 and j > i:
                break
        out.append((i + 1, body))
    return out


def strip_ratio(prelude):
    """`@media (max-aspect-ratio: 3/2) and (min-height: 421px) {` ->
       `@media (min-height: 421px) {`   — and the lone-term case to `all`."""
    p = re.sub(r"\(\s*max-aspect-ratio\s*:[^)]*\)\s*and\s*", "", prelude)
    p = re.sub(r"\s*and\s*\(\s*max-aspect-ratio\s*:[^)]*\)", "", p)
    if re.match(r"^@media\s*\{", p.strip()):
        p = "@media all {"
    return p


blocks = find_blocks()
if not blocks:
    sys.exit("gen-ios10-layout: no max-aspect-ratio media blocks in sidecrab.css — "
             "upstream changed shape; this script needs rereading, not rerunning.")

chunks = []
for start, body in blocks:
    prelude = strip_ratio(body[0])
    inner = body[1:-1]
    chunks.append(
        "/* ---- sidecrab.css:%d ----\n   was: %s */\n@supports not (gap: 1px) {\n%s\n%s\n}\n}\n"
        % (start, body[0].strip(), prelude, "\n".join(inner))
    )

CORRECTIONS = """

/* =====================================================================
   Hand-maintained: gap fallbacks these layouts invalidate
   =====================================================================

   NOT generated — regenerating the file above must not drop this.

   ios10-compat.css replaces every `gap` with a margin, and the axis it picks is
   the container's flex-direction AT THE AUTHORED SLOT. Two of the blocks above
   flip a direction, which silently turns the right margin into the wrong one:

     NEAR-SQUARE flips .zone-identity to `flex-direction: row` (sidecrab.css:3419)
     PORTRAIT    flips .zone-limits   to `flex-direction: row` (sidecrab.css:3523)

   Both were column at the 2560x720 slot, so both carry a margin-top from the
   compat layer that has to become a margin-left here. The auto margins are
   re-cleared for the same reason they were asserted there: on a row they anchor
   nothing and would push their sibling to the far edge. */

@supports not (gap: 1px) {

	/* ---- THE ROOT OF EVERYTHING BELOW ----

	   .zones is `flex: 1 1 auto` with no stated height, and every height in the
	   panel is a percentage of it: the band's 29%, the two zones' 71%, .crab's
	   100%, and the `repeat(2, minmax(0, 1fr))` rows of the card grid. A flex
	   item's height is definite enough for those percentages in a modern engine
	   and NOT in this one, so all of them silently resolved to auto — which is
	   one cause with four faces: the crab inflated to its intrinsic ratio, the
	   band grew to hold it, the two zones fell off the bottom of the screen, and
	   the grid rows sized to content so two cards filled the whole zone.

	   Stating the height makes the whole chain resolvable again. flex-shrink is
	   untouched, so the banner still gets its space on the rare frame it appears. */
	.zones { height: 100%; }

	@media (min-height: 421px) and (min-width: 641px) {
		:root {
			/* TUNE THESE TWO. Everything else in this block is derived. */
			--legacy-crab-h: calc(var(--fs-clock) * 1.25);
			--legacy-band-gap: calc(var(--layout-unit) * 6);
			/* Row height for the card grid. A BARE length, never calc(): see the
			   .cards rule for why the serialization of this value decides how many
			   cards get rendered. */
			--legacy-card-row: 15vmin;
			/* The band is the crab plus .zone's own padding, top and bottom. */
			--legacy-band-h: calc(var(--legacy-crab-h) + var(--space-pad) * 2);
			/* The header at the touch floor it already carries as a minimum, plus
			   its 1px border top and bottom, so .cards can be given the remainder. */
			--legacy-head-h: calc(var(--touch-min) + 2px);
		}

		/* Restated rather than inherited: this block is the one that has to hold
		   even if a later upstream edit moves the band's direction around. */
		.zone-identity {
			height: auto;
			flex-direction: row;
			align-items: center;
			justify-content: center;
		}
		/* .clock is `width: 100%` at the authored slot, where the band is a COLUMN
		   and 100% is the right answer. In a row it makes the clock as wide as the
		   whole zone, which is what put it over the crab. The shared block already
		   says `width: auto`; restated here because being wrong about this looks
		   exactly like the gap being too small, and cost a round trip to tell apart. */
		.clock { flex: 0 0 auto; width: auto; }
		.zone-identity > * + * { margin-top: 0; margin-left: var(--legacy-band-gap); }

		/* ---- the crab is sized to the clock, not to the row ----

		   .crab is `width: 100%; height: 100%` inside .crab-wrap, which is
		   `flex: 1 1 auto` with no definite height of its own. When the percentage
		   height does not resolve — which is the same missing definite-height chain
		   that stopped the sheet scrolling — an <svg> with a viewBox falls back to
		   its INTRINSIC ratio and derives its height from its width. In the
		   near-square band that width is most of 1024px, so the crab inflates to
		   several hundred px, takes the whole band with it and pushes Limits and
		   Sessions off the bottom of a screen that has body{overflow:hidden}.

		   So the band is measured off the crab rather than the other way round.
		   Height is stated in --fs-clock units to sit beside the clock by
		   construction, and the width is stated explicitly rather than left to the
		   SVG's intrinsic ratio, because relying on that ratio is what caused this.
		   52/44 is the viewBox (0 -4 52 44), so 1.182.

		   TO TUNE: change the 1.25 below and nothing else. The viewBox carries ~10
		   units of empty headroom above the shell and ~6 below the legs, so the
		   PAINTED animal is about 28 of its 44 units — the box has to run a little
		   taller than the clock for the crab to read as the same size as it.

		   THE ORDER OF THESE TWO RULES IS A DEPENDENCY, not a preference. The shared
		   block above sets `.crab-wrap { flex: 1 1 0 }` and says why: flex-basis 0,
		   NOT auto, because `.crab { width: 100% }` inside an auto-width flex item is
		   circular — upstream measured the wrap coming out 0 px wide and the clock
		   overflowing the zone by 214 px. Going back to basis auto here is only safe
		   BECAUSE the crab below is given an explicit width in the same breath, which
		   breaks that circularity. Restore any percentage width on .crab and the wrap
		   collapses to zero and takes the clock with it. */
		.crab-wrap { flex: 0 0 auto; width: auto; }
		.crab {
			height: var(--legacy-crab-h);
			max-height: var(--legacy-crab-h);
			width: calc(var(--legacy-crab-h) * 1.182);
		}
		/* ---- the two zones take the exact remainder ----

		   Not the 71% upstream states, because the band above is now `auto` rather
		   than 29% and the two no longer add up. With .zones stated this resolves,
		   which is what finally gives .cards a definite height — and a definite
		   height is the whole reason `grid-template-rows: repeat(2, minmax(0, 1fr))`
		   can put eight cards on the glass instead of letting two fill the zone.
		   The 1px is .zone-identity's border-bottom. */
		.zone-limits,
		.zone-grid { height: calc(100% - var(--legacy-band-h) - 1px); }

		/* ---- the card grid scrolls, and renders more to scroll through ----

		   .cards is `flex: 1 1 auto` inside .zone-grid, so even with the zone's own
		   height now stated, the grid container's height is flex-determined — and
		   that is not definite enough here for `repeat(2, minmax(0, 1fr))` to divide.
		   The rows fall back to content height, the second row runs past the zone,
		   and body{overflow:hidden} takes the bottom off it. The same failure as
		   .zones, one level down, and it cannot be closed the same way: what sits
		   above .cards is .grid-head, whose height is its content, so there is no
		   honest calc() to write.

		   So it scrolls instead — which is the better answer regardless. A fixed 2x4
		   grid can only ever show 8, and a panel whose job is to answer "what is
		   waiting on me" should not leave the operator wondering what is off-screen.

		   FOUR EXPLICIT ROWS, NOT grid-auto-rows. gridCapacity() decides how many
		   cards to render by counting the computed tracks of both axes, and its
		   reader requires px/fr/% in the string (sidecrab.js:2822) — so
		   `grid-template-rows: none` plus grid-auto-rows would fall through to its
		   default of 2 and render 8 cards into a grid with room to scroll 16.
		   Upstream's rule is that the stylesheet owns both axes and gridCapacity
		   owns neither; this keeps that bargain instead of working around it.

		   A DEFINITE HEIGHT IS THE WHOLE POINT, and the first attempt at this rule
		   missed it: `overflow-y: auto` scrolls nothing on a box whose height is its
		   own content. .cards is `flex: 1 1 auto`, so it just grew and overflowed
		   the zone exactly as before, now with a scrollbar declared on it. It needs
		   a stated height, and the only unknown between it and the zone is
		   .grid-head — so that is stated too, at the touch floor it already carries
		   as a minimum, plus its border. `flex: 0 0 auto` then stops the height
		   being flexed away again.

		   AND THE ROWS HAVE TO BE ABLE TO EXCEED IT. The first attempt used four 25%
		   tracks, which was self-defeating twice over: against an indefinite height
		   they behave as auto, and against the definite height this rule now gives,
		   four 25% rows fill the box exactly — nothing overflows, so there is still
		   nothing to scroll, and every card is squeezed into a quarter of the zone.
		   Fixed rows overflow, and the overflow is the scroll.

		   THE TRACK FORM IS CHOSEN FOR HOW IT SERIALIZES. trackCount() splits the
		   computed string on whitespace and counts the pieces (sidecrab.js:2822), so
		   the answer depends on whether this engine serializes grid-template-rows as
		   used track sizes or as written — which is untestable from here. Four bare
		   var() references substitute to `15vmin` x4 before serialization, so:
		       used      -> "115.2px" x4 -> 4 tracks        -> capacity 16
		       specified -> "15vmin" x4  -> no px|fr|% ->     GRID_ROWS default 2 -> 8
		   Both are sane. Anything carrying calc() would have counted 12 pieces under
		   the second reading and rendered 48 cards onto a 2012 A6X.

		   touch-action carves the vertical axis back out of `.zones { touch-action:
		   none }`, which upstream declares because nothing in there scrolls — true
		   until this rule. It is a no-op on the device this file is for (full
		   touch-action is Safari 13, the same release that brought Pointer Events,
		   so every browser needing this file ignores it), and it is what makes the
		   scroll work on the Safari 12-14 range that lands in the same block.

		   BOTH SELECTORS, because density is forced to compact here and upstream's
		   `body.density-compact .cards` is (0,2,0) — a bare .cards would lose. */
		.grid-head { height: var(--legacy-head-h); }
		.cards,
		body.density-compact .cards {
			flex: 0 0 auto;
			height: calc(100% - var(--legacy-head-h) - var(--space-gap));
			grid-template-rows: var(--legacy-card-row) var(--legacy-card-row) var(--legacy-card-row) var(--legacy-card-row);
			align-content: start;
			overflow-y: auto;
			-webkit-overflow-scrolling: touch;
			touch-action: pan-y;
		}

		/* ---- the header stops writing over itself ----

		   The <=3:2 block gives .session-count `white-space: normal; overflow:
		   visible` so the day recap wraps instead of ellipsising — measured for an
		   840px slot, where 437px of text had 302.6px of box. A flex item that is
		   `flex: 0 1 auto; min-width: 0` and overflows VISIBLY paints outside its
		   box when the row squeezes it, and with margin-left:auto holding it right,
		   what it paints over is the "SESSIONS" label to its left.
		   This slot is 1024px, not 840, so the base one-line behaviour fits far
		   better here than it did there. Ellipsising the tail is the cost, and the
		   whole recap is one tap away: .grid-head opens today's timeline. */
		.session-count { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

	}
	@media (min-height: 421px) and (max-width: 640px) {
		.zone-limits > * + * { margin-top: 0; margin-left: var(--space-gap); }
		.zone-limits > .today,
		.zone-limits > .sensors.shown { margin-top: 0; }
	}
}
"""

ref = ", ".join(str(s) for s, _ in blocks)
out = HEADER % ref + "\n".join(chunks) + CORRECTIONS

# A malformed comment emits VALID-LOOKING but broken CSS: the rules after a stray
# `*/` are parsed as declarations, dropped, and the browser recovers silently at
# the next `}`. It cost a round trip once. Never ship it unchecked again.
n_open, n_close = out.count("/*"), out.count("*/")
if n_open != n_close:
    sys.exit("gen-ios10-layout: %d `/*` vs %d `*/` — a comment is unbalanced, "
             "which would emit broken CSS silently." % (n_open, n_close))
stripped = re.sub(r"/\*.*?\*/", "", out, flags=re.S)
if stripped.count("{") != stripped.count("}"):
    sys.exit("gen-ios10-layout: unbalanced braces outside comments (%d vs %d)."
             % (stripped.count("{"), stripped.count("}")))
# Exact rather than heuristic: walk the text and flag a `*/` that closes nothing.
# That is the precise shape of the bug — a comment closed early, so its remaining
# prose lands in the stylesheet — and counting alone cannot catch it when a later
# stray `/*` rebalances the totals.
depth, i = 0, 0
while i < len(out) - 1:
    two = out[i:i + 2]
    if two == "/*":
        depth += 1
        i += 2
        continue
    if two == "*/":
        depth -= 1
        if depth < 0:
            line = out.count("\n", 0, i) + 1
            sys.exit("gen-ios10-layout: `*/` at line %d closes no comment — the "
                     "prose after it would be emitted as CSS." % line)
        i += 2
        continue
    i += 1

open(OUT, "w", encoding="utf-8").write(out)
print("gen-ios10-layout: %d blocks, comments and braces balanced -> %s"
      % (len(blocks), os.path.normpath(OUT)))
